"$schema" = 'https://starship.rs/config-schema.json'


format = """
  $os\
$directory\
$git_branch\
$git_status\
$gcloud\
$azure\
$aws\
$bun\
$buf\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$gradle\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$meson\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$red\
$rlang\
$ruby\
$rust\
$solidity\
$typst\
$swift\
$vagrant\
$vlang\
$zig\
$cmd_duration\
$fill\
$time\
$line_break\
$character\
"""

add_newline = true
continuation_prompt = "[â–¸â–¹ ](dimmed white)"

[cmd_duration]
format = "[â± $duration]($style)"
min_time = 1000

[fill]
style = "fg:#bfbfbf"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = ' [ïº $time]($style) '
style = "italic white"

[os]
disabled = false

[os.symbols]
Windows = "ó°² "
Ubuntu = "ó°•ˆ "
SUSE = "ïŒ” "
Raspbian = "ó°¿ "
Mint = "ó°£­ "
Macos = "ó°€µ "
Manjaro = "ïŒ’ "
Linux = "ó°Œ½ "
Gentoo = "ó°£¨ "
Fedora = "ó°£› "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ó°£‡ "
EndeavourOS = "ï†— "
CentOS = "ïŒ„ "
Debian = "ó°£š "
Redhat = "ó±„› "
RedHatEnterprise = "ó±„› "
Pop = "ïŒª "


[line_break]
disabled = false

[character]
format = "$symbol "
success_symbol = "[â—](bold italic bright-green)"
error_symbol = "[â—‹](italic purple)"
vimcmd_symbol = "[â– ](italic dimmed green)"
vimcmd_replace_one_symbol = "â—Œ"
vimcmd_replace_symbol = "â–¡"
vimcmd_visual_symbol = "â–¼"

[git_branch]
symbol = "ï˜"
format = '[[ $symbol $branch ](fg:#93DA97)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status $ahead_behind)]()]($style)'

[directory]
home_symbol = "âŒ‚"
truncation_length = 2
truncation_symbol = "â—ˆ "
use_os_path_sep = true
format = '[ $path ]($style bold fg:#FE7743)'

[bun]
symbol = "ó°¡„ "
format = '[[ $symbol( $version) ](fg:#fbf1c7)]($style)'

[buf]
symbol = "î¯™ "
format = '[[ $symbol( $version) ](fg:#1fb3d4)]($style)'

[cmake]
symbol = "î™³ "
format = '[[ $symbol( $version) ](fg:#064f8c)]($style)'

[cobol]
symbol = "ó°›“ "
format = '[[ $symbol( $version) ](fg:#005ca5)]($style)'

[crystal]
symbol = "î˜¯ "
format = '[[ $symbol( $version) ](fg:#000100)]($style)'

[daml]
symbol = "ó°„„ "
format = '[[ $symbol( $version) ](fg:#0194d2)]($style)'

[dart]
symbol = "î˜ "
format = '[[ $symbol( $version) ](fg:#00b4ab)]($style)'

[deno]
symbol = "îŸ… "
format = '[[ $symbol( $version) ](fg:#000000)]($style)'

[dotnet]
symbol = "ó°ª® "
format = '[[ $symbol( $version) ](fg:#512bd4)]($style)'

[elixir]
symbol = "î‰µ "
format = '[[ $symbol( $version) ](fg:#6e4a7e)]($style)'

[elm]
symbol = "î˜¬ "
format = '[[ $symbol( $version) ](fg:#1293d8)]($style)'

[erlang]
symbol = "î± "
format = '[[ $symbol( $version) ](fg:#a90533)]($style)'

[fennel]
symbol = "ó°¬™ "
format = '[[ $symbol( $version) ](fg:#fff3d0)]($style)'

[gleam]
symbol = "ó°›¨ "
format = '[[ $symbol( $version) ](fg:#ffaff3)]($style)'

[golang]
symbol = "î˜§ "
format = '[[ $symbol( $version) ](fg:#00add8)]($style)'

[gradle]
symbol = "î™  "
format = '[[ $symbol( $version) ](fg:#02303a)]($style)'

[haxe]
symbol = "î™¦ "
format = '[[ $symbol( $version) ](fg:#ec7d0c)]($style)'

[helm]
symbol = "ïˆš "
format = '[[ $symbol( $version) ](fg:#277a9f)]($style)'

[java]
symbol = "î‰– "
format = '[[ $symbol( $version) ](fg:#007396)]($style)'

[julia]
symbol = "î˜¤ "
format = '[[ $symbol( $version) ](fg:#a270ba)]($style)'

[kotlin]
symbol = "î˜´ "
format = '[[ $symbol( $version) ](fg:#a97bff)]($style)'

[lua]
symbol = "î˜  "
format = '[[ $symbol( $version) ](fg:#000080)]($style)'

[meson]
symbol = "ó°”¶ "
format = '[[ $symbol( $version) ](fg:#0078d7)]($style)'

[nim]
symbol = "ó°†¥ "
format = '[[ $symbol( $version) ](fg:#ffe953)]($style)'

[nodejs]
symbol = "îœ˜ "
format = '[[ $symbol( $version) ](fg:#68a063)]($style)'

[ocaml]
symbol = "î™º "
format = '[[ $symbol( $version) ](fg:#ec6813)]($style)'

[opa]
symbol = "ó±„ "
format = '[[ $symbol( $version) ](fg:#4478e3)]($style)'

[perl]
symbol = "î© "
format = '[[ $symbol( $version) ](fg:#39457e)]($style)'

[php]
disabled = true
symbol = "î˜ˆ "
format = '[[ $symbol( $version) ](fg:#8892be)]($style)'

[pulumi]
symbol = "ó±¢ "
format = '[$symbol$stack]($style) '

[purescript]
symbol = "î˜° "
format = '[[ $symbol( $version) ](fg:#1d222d)]($style)'

[python]
symbol = "î˜† "
format = '[[ $symbol( $version) ](fg:#3572a5)]($style)'

[quarto]
symbol = "ó°—€ "
format = '[[ $symbol( $version) ](fg:#2d5f9a)]($style)'

[raku]
symbol = "îŠ’ "
format = '[[ $symbol( $version) ](fg:#00006e)]($style)'

[red]
symbol = "ó°“† "
format = '[[ $symbol( $version) ](fg:#f50000)]($style)'

[rlang]
symbol = "ó°Ÿ” "
format = '[[ $symbol( $version) ](fg:#1e90ff)]($style)'

[ruby]
symbol = "î‘ "
format = '[[ $symbol( $version) ](fg:#cc342d)]($style)'

[rust]
symbol = "î¨ "
format = '[[ $symbol( $version) ](fg:#dea584)]($style)'

[solidity]
symbol = "î™– "
format = '[[ $symbol( $version) ](fg:#3c3c3d)]($style)'

[typst]
symbol = "ó±˜ "
format = '[[ $symbol( $version) ](fg:#239dad)]($style)'

[swift]
symbol = "î• "
format = '[[ $symbol( $version) ](fg:#fa7343)]($style)'

[vagrant]
symbol = "ó°¡¨ "
format = '[[ $symbol( $version) ](fg:#1563ff)]($style)'

[vlang]
symbol = "îš¬ "
format = '[[ $symbol( $version) ](fg:#5d87bf)]($style)'

[zig]
symbol = "îš© "
format = '[[ $symbol( $version) ](fg:#f7a41d)]($style)'

[gcloud]
format = '[ï· $account on $project]($style) '
style = 'green bold'
disabled = true

[azure]
format = '[$symbol($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'
disabled = true

[aws]
format = '[$symbol $profile on $region]($style) '
style = 'bold fg:#bf5700'
symbol = 'ğŸ…° '
disabled = true

[docker_context]
symbol = "ïŒˆ"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
